spring:
  application:
    name: chzzkbot
    version: 0.0.1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/guribot
    username: guribot
    password: guribot
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
  security:
    user:
      name: guribot
      password: guribot
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    clear-checksums: false
server:
  port: 8180
security:
  allowed-uris: /,/css/**,/js/**,/register
  authenticated-uris: /commandList
logging:
  level:
    org.springframework.messaging: error
    org.springframework.web.socket: error
    org.hibernate: error
    liquibase: error
chzzk:
  bot:
    name: "뮤쪽이"
    openingMessage: "나님 등장!"
    closingMessage: "나님도 자러갈게..."
  ChannelName: 뮤로나
  URL:
    chzzkBaseURL: https://api.chzzk.naver.com/
    gameBaseURL: https://comm-api.game.naver.com/
    naverBaseURL: https://apis.naver.com/
user:
  agent: ${spring.application.name}/${spring.application.version}-(Spring-boot)
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost