spring:
  application:
    name: chzzkbot
    version: 0.0.1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/guribot
    username: guribot
    password: guribot
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
  security:
    user:
      name: guribot
      password: guribot
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    clear-checksums: false
server:
  port: 8080
security:
  allowed-uris: /,/admin,/test,/command
logging:
  level:
    org.springframework.messaging: debug
    org.springframework.web.socket: debug
    liquibase: debug
chzzk:
  NID_AUT: pAw0ywM4695bUa+qqaSGbcqA9JOPDJaeOULYkcOuQTerI63laYiFwJmaHITG8ux6
  NID_SES: AAABjsCrfHWyoI7Gd2NCKi0WAOJIrOb5flAsbiUe1LWk4vtmpRWYjAy/O4BH4iVs0kKg6cJNmkbT8FH9bnB23N7U6rnaPY4y7n3IiU0RaQQtqCq1zHY1HTGNoxGwH5gWh92yLE07wkn7PEbk1EESQ4hIVcN3Sm2qUvMOPXqWbyf6xihdJxOG3xOM7r3a7YStjEgQtvZzG0PUzDBaUE9MQhr0k1UbMBUGZsJP8My2dMo8MIzApWJzKBlQEaBzPFzSF+H4+J1ye3hifi9N20lkGHKe8XlVXmkXCNyJR0J6PkF5TBNgxMwy3+kHWWrTDM4YMwK/3OQR8uL9fpshg648/S8otrBBltmu/tNmo6plwMEdQfO+10XLQMMDDr8YbAG+YkKEntwN83g2uicUC2KC8cMg1mi5W1KcPXjZwFBTEkanphV+5gvcFkQvyzzgMIFWYXhawrcA+IFCYiLhOxSQYGGmnQych9TzbvKGaQUEhdoNAZQgcEp2/3r0eAMpZuwa6KgKauM1IiopiuUiiv52BXrilXM=
  ChannelName: 뮤로나
  #ChannelId: 448acb33aff5339a08540f0d9e8e2652
  URL:
    chzzkBaseURL: https://api.chzzk.naver.com/
    gameBaseURL: https://comm-api.game.naver.com/
    naverBaseURL: https://apis.naver.com/
user:
  agent: chzzkBot/0.0.1 (Spring-boot)
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    hostname: localhost